//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculate.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PenaltyCalculateEntities : DbContext
    {
        public PenaltyCalculateEntities()
            : base("name=PenaltyCalculateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblholiday> tblholiday { get; set; }
        public virtual DbSet<tblCountryMasterDetails> tblCountryMasterDetails { get; set; }
    }
}
