//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblholiday
    {
        public int ID { get; set; }
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> NationalHoliday { get; set; }
    }
}
